### ISSUE TITLE
Page chat : Permettre aux utilisateur de communiquer entre eux.

### ISSUE THREAD

**Issue by KGabard** [KGabard/OC_P10_LearnAtHome#27]
Fonctionnalité associée à la user story #13.

### Description
La page de chat doit permettre de voir les différente conversations d'un utilisateur avec ses contacts. Elle doit également permettre de leur rédiger des messages.

### To-Do
- [ ] Intégrer le design de la page
- [ ] Créer l'interface de chat
- [ ] Gérer la sauvegarde des conversations
- [ ] Implémenter le système de recherche de contact

![Image](https://user-images.githubusercontent.com/100465313/212688447-e3d61550-146e-4ad9-b785-a6431cbec5e2.png)
