### ISSUE TITLE
Design : Rendre le design du site responsive sur bureau, tablette et mobile.

### ISSUE THREAD

**Issue by KGabard** [KGabard/OC_P10_LearnAtHome#32]
### To-Do
- [ ] Responsive de la page de connexion
- [ ] Responsive de la page tableau de bord
- [ ] Responsive de la page tâches
- [ ] Responsive de la page calendrier
- [ ] Responsive de la page chat
